### PR TITLE
Update Project.toml's compat

### PR DESCRIPTION
**Pull request by ashwanirathee**
- It wasn't working with Images 0.25

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
1 test fails

**Comment by timholy** [comment]
xref #103

**Comment by timholy** [comment]
After we merge this, perhaps we should slim the dependencies down to ImageCore and other specific packages (including ImageCorners). That might make it possible to move this into Images someday.

**Comment by timholy** [comment]
This won't pass tests but I have local fixes.

**Comment by timholy** [comment]
BTW I disabled testing on nightly, see https://discourse.julialang.org/t/why-do-packages-run-continuous-integration-tests-on-julia-nightly/101208/3?u=tim.holy

**Pull request merged**
