### PR TITLE
Change `sampled_intensities` `eltype` in `create_descriptor` for FREAK and BRISK

### LINKED ISSUE #107: `sampled_intensities` `eltype` issue in `create_descriptor` for FREAK and BRISK
In the `create_descriptor` functions for FREAK and BRISK, the `sampled_intensities` array is declared with the same type of the input image, but it should be declared with the same type as the integral image of the input image.

For some images I'm working with, it leads to the following error:
```julia
julia> using Images, ImageFeatures
       img = load("test_image.png")
       img1 = Gray.(img)::Matrix{Gray{N0f8}} 
       feats_1 = Features(fastcorners(img1, 20, 0.5))
       brisk_params = BRISK()
       desc_1, ret_feats_1 = create_descriptor(img1, feats_1, brisk_params)
       nothing
ERROR: ArgumentError: element type N0f8 is an 8-bit type representing 256 values from 0.0 to 1.0,
  but the values (1.0034722f0,) do not lie within this range.
  See the READMEs for FixedPointNumbers and ColorTypes for more information.
Stacktrace:
  [1] throw_colorerror_(#unused#::Type{N0f8}, values::Tuple{Float32})
    @ ColorTypes ~/.julia/packages/ColorTypes/1dGw6/src/types.jl:686
  [2] throw_colorerror(#unused#::Type{Gray{N0f8}}, values::Tuple{Float32})
    @ ColorTypes ~/.julia/packages/ColorTypes/1dGw6/src/types.jl:736
  [3] checkval
    @ ~/.julia/packages/ColorTypes/1dGw6/src/types.jl:648 [inlined]
  [4] Gray
    @ ~/.julia/packages/ColorTypes/1dGw6/src/types.jl:359 [inlined]
  [5] _convert
    @ ~/.julia/packages/ColorTypes/1dGw6/src/conversions.jl:96 [inlined]
  [6] cconvert
    @ ~/.julia/packages/ColorTypes/1dGw6/src/conversions.jl:76 [inlined]
  [7] convert
    @ ~/.julia/packages/ColorTypes/1dGw6/src/conversions.jl:73 [inlined]
  [8] push!
    @ ./array.jl:1060 [inlined]
  [9] create_descriptor(img::Matrix{Gray{N0f8}}, features::Vector{Feature}, params::BRISK)
    @ ImageFeatures ~/.julia/dev/ImageFeatures/src/brisk.jl:95
 [10] top-level scope
    @ REPL[1]:6
```
Here is the test image, to reproduce the issue if needed:
test_image

The fix could be to replace 
https://github.com/JuliaImages/ImageFeatures.jl/blob/5c277fdaac902794196840212ebf0994a6b0fa34/src/brisk.jl#L92
by
```julia
        sampled_intensities = eltype(int_img)[]
```

### PR DESCRIPTION
**Pull request by mathieu17g**
Fixes https://github.com/JuliaImages/ImageFeatures.jl/issues/107

### CODE REVIEW

**Review by ashwanirathee — APPROVED** [review]
Looks good to me!

**Comment by timholy** [comment]
Thanks, this is great! Would it be too much to ask for a test? That way it is far more likely to stay fixed in the future.

**Comment by mathieu17g** [comment]
Ok I will look into the TestImages package, for an image (possibly slightly modified) exhibiting the issue #107

**Comment by mathieu17g** [comment]
Tests added for both BRISK and FREAK

**Comment by mathieu17g** [comment]
Tests added for both BRISK and FREAK

**Comment by timholy** [comment]
Great, thanks!

**Pull request merged**
