### PR TITLE
Fix type instability and use views to reduce memory allocation

### PR DESCRIPTION
**Pull request by zygmuntszpak**
The proposed change results in an approximately four-fold reduction in run-time.

### CODE REVIEW

**Comment by zygmuntszpak** [comment]
Benchmark:
```julia
using Images, ImageFeatures, TestImages, BenchmarkTools

img = testimage("cameraman")
create_descriptor(img, HOG())
@time create_descriptor(img, HOG())
```

Before changes: ` 0.132088 seconds (6.07 M allocations: 115.611 MiB, 18.21% gc time)`
After changes:  ` 0.029706 seconds (37.65 k allocations: 21.159 MiB, 11.03% gc time)`

**Comment by zygmuntszpak** [comment]
@Evizero The builds failed on some architectures, but the fails are related to the `BRISK` feature and not the code that I have modified here.

**Comment by Evizero** [comment]
I added you to the ImageFeatures group to give you write access. 

I am sure you have a better understanding of this domain than I have. As far as I am concerned I have complete trust in your judgment on merging PRs for this package.

That said I am always happy to review code if you would like a second opinion on the "Julia" aspect

**Review by Evizero — APPROVED** [review]

**Comment by zygmuntszpak** [comment]
Just making a note of what caused the build failure. It looks like `TestImages` failed to download `Lena` which caused `brief.jl` to fail. 
```julia
Test Summary: | Pass  Total
core.jl       |   15     15
INFO: Could not find lighthouse in directory. Checking if it exists in the online repository.
INFO: Found lighthouse in the online repository. Downloading to the images directory.
INFO: Could not find lena_gray_512 in directory. Checking if it exists in the online repository.
INFO: Found lena_gray_512 in the online repository. Downloading to the images directory.
Testing with Standard Images - Lena (Translation (10, 20)): Error During Test
  Got an exception of type ErrorException outside of a @test
  automatic download failed (error: 2148270092): https://github.com/JuliaImages/TestImages.jl/blob/gh-pages/images/lena_gray_512.tif?raw=true
  Stacktrace:
   [1] download(::String, ::String) at .\interactiveutil.jl:577
   [2] testimage(::String) at C:\Users\appveyor\.julia\v0.6\TestImages\src\TestImages.jl:68
   [3] macro expansion at C:\Users\appveyor\.julia\v0.6\ImageFeatures\test\brief.jl:169 [inlined]
   [4] macro expansion at .\test.jl:860 [inlined]
   [5] anonymous at .\<missing>:?
   [6] include_from_node1(::String) at .\loading.jl:569
   [7] include at .\sysimg.jl:14
   [8] macro expansion at C:\Users\appveyor\.julia\v0.6\ImageFeatures\test\runtests.jl:64 [inlined]
   [9] macro expansion at .\test.jl:860 [inlined]
   [10] macro expansion at C:\Users\appveyor\.julia\v0.6\ImageFeatures\test\runtests.jl:63 [inlined]
   [11] anonymous at .\<missing>:?
   [12] include_from_node1 at .\loading.jl:569
   [13] include at .\sysimg.jl:14
   [14] process_options at .\client.jl:305
   [15] _start at .\client.jl:371
Test Summary:                                                        | Pass  Error  Total
brief.jl                                                             |  225      1    226
  Sampling Patterns                                                  |  216           216
  Descriptor Calculation                                             |    3             3
  Testing with Standard Images - Lighthouse (Translation (100, 200)) |    1             1
  Testing with Standard Images - Lena (Translation (10, 20))         |           1      1
ERROR: LoadError: Some tests did not pass: 225 passed, 0 failed, 1 errored, 0 broken.
while loading C:\Users\appveyor\.julia\v0.6\ImageFeatures\test\runtests.jl, in expression starting on line 62
============================[ ERROR: ImageFeatures ]============================
```

**Pull request merged**
