### PR TITLE
switch to new registrator and drop CI support for julia 0.7

### PR DESCRIPTION
**Pull request by johnnychen94**
I also rewrite the travis script in a cleaner way.

More details: https://github.com/JuliaImages/Images.jl/issues/798

Blocking package:

- [x] Images: https://github.com/JuliaImages/Images.jl/pull/800
- [x] FixedPointNumbers https://github.com/JuliaMath/FixedPointNumbers.jl/pull/119
~- [ ] QuartzImageIO: https://github.com/JuliaIO/QuartzImageIO.jl/pull/56~

### CODE REVIEW

**Comment by timholy** [comment]
Hopefully the Distributions error will be fixed by https://github.com/JuliaStats/Distributions.jl/issues/868

**Comment by johnnychen94** [comment]
😄 I made some changes there yesterday.

**Comment by timholy** [comment]
I noticed, thanks! Just waiting for a release (which is stuck due to a registrator bug).

**Comment by timholy** [comment]
We can fix the docs later.

**Pull request merged**
